# Generated by Django 2.1.7 on 2019-03-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('code_name', 'date')},
        ),
    ]
